### ISSUE TITLE
Buff/nerf a few units please!

### ISSUE THREAD

**Issue by OZEuncubeus** [Team-OZE/LegionTD-Map#120]
- Medicine Man back to 110
- Hatchling to 160 hp
- Violet nerf 100 HP, nerf 1 ability dmg by 1
- Moonguard to 255 gold

**Comment by STOPTHECOUNT** [comment]
Isn't Violet already super weak? You sure you wanna nerf it?

**Comment by STOPTHECOUNT** [comment]
You want to buff warden from 20% evasion to 25%?
