### ISSUE TITLE
Buff Ghost

### ISSUE THREAD

**Issue by OZETobi** [Team-OZE/LegionTD-Map#14]
**Is your feature request related to a problem? Please describe.**
Ghost is currently useless as the range of the spell aura is shorter than the range of the Ghost. 

**Describe the solution you'd like**
Buff Ghost spell range back to original. Change 1% dmg per sec to 1% dmg per 2 seconds.

**Comment by OZEuncubeus** [comment]
Range was 300 right?

**Comment by STOPTHECOUNT** [comment]
Yep

**Comment by OZEuncubeus** [comment]
> Yep

So needs to be 400 again

**Comment by OZEuncubeus** [comment]
Either this: 
1. Every unit affected by heartstopper aura loses 1% of max HP +1 per second
2. Every unit affected by heartstopper aura loses 1% of max HP +2 per second
3. Or completely remove extra dmg on top of 1%

Originally: Every unit affected by heartstopper aura loses 1% of max HP +3 per second

**Comment by STOPTHECOUNT** [comment]
Done in #111
