### ISSUE TITLE
Hades Manapool

### ISSUE THREAD

**Issue by Jakob219** [Team-OZE/LegionTD-Map#140]
Change Hades manapool from 60 to 120. otherwise it was too strong with messiah

**Comment by OZEuncubeus** [comment]
Or regen like schachmat suggested. As long as the respawn time isn't less than 30 sec with messiah buff

**Comment by Jakob219** [comment]
yeah multiply manaregen by 0.5 please, instead of touching the manapool.

**Comment by OZEuncubeus** [comment]
**Also lord of death needs a similar nerf because of the mana regen rate with messiah**
