### ISSUE TITLE
tooltip mismatch and melee range accuracy

### ISSUE THREAD

**Issue by OZEuncubeus** [Team-OZE/LegionTD-Map#146]
**dragon aspect** has less damage in builder phase than in combat phase. (only combat phase has same value as tooltip say)

same is with **harpies**. change atk damage from builderphase unit

**tribesman** damage on tooltip and damage from builder+fighter unit is wrong.

**dwarven engineer** differs combat/build unit
in damage

**neo tanks** range in tooltip shows 600, in builder unit its 450, and in fighter unit its 600 again

**destroyers** builder unit shows 400 range, fighter unit then has 235 range.

-still remove mana bar of **tree of battle**

yggdrasil's tooltip shows -102 damage, builder unit has -101 damage kekw, fighter unit as well!

range (mismatch):

eg at **gnolls**, they show "100" when hovered above the atk tooltip
and upped gnolls have the 150 then
_and other units show "melee" when hovered_

golem and mud golem show at tooltip "range 100" although they are pure melee

**Ogre** tooltip says range 100
but it has range "melee" -same with **ogre pulverizer**

**Comment by OZEuncubeus** [comment]
Before build Attack dmg tooltip **hydra** incorrect

**Comment by OZETobi** [comment]
**Gnoll Savage**
- Before round start the dmg is 64-68. After round start the dmg is 65-69. Should be 65-69 always.
- In the upgrade-icon from Gnoll Warrior it also shows 64-68. Change to 65-69.

**Harpy**
- Before round start HP is 425. After round start the HP is 325. Change all to 325.

**Medusa**
- Before round start Dmg is 56-63. After round start Dmg is 61-68. Change all to 61-68.

**Troll Champion**
- Adrenaline Rush "Status-Text" says: "This unit has increased attack speed." It should say: "This unit has increased attack speed and movement speed.

**Greymane**
- Battle Cry “Status-Text” says: “This unit damage has been increased." It should say: “The damage and armor of this unit has been increased.”

**Spawn of Dragon**
- The "Upgrade-Icon" to Dragon Aspect shows attack dmg 260-266. But the real dmg of Dragon Aspect is 260-275.

**Veteran**
- Change tooltip to: “This unit has a 5% chance to do 60 times normal damage on an attack”

**Zeus**
- Before round starts Dmg is 16-18. After round starts Dmg is 25-27. Change all to 25-27.

**Pyro**
- The "Upgrade-Icon" to Destroyer calls ability "Triple Attack". But the ability of Destroyer is named "Triple Fire Ball"

**Destroyer**
- Change spell tooltip to: “Every time this unit attacks, it hits 3 additional enemies with fireballs for 40 damage each.”

**Leviathan**
- Change ability tooltip to: “Every time this unit attacks, it has a 40% chance of releasing bomb shrapnel which will deal 50 damage to 3 nearby enemies.”

**Cyborg**
- "Upgrade-Icon" to Krogoth shows 156-164 dmg. But the dmg of Krogoth is 176-184.

**Comment by Jakob219** [comment]
aqua spirits +oceanus tooltip say fighter units attack, builder unit is outdated.

also range of aquaspirit (builder) changes from 375 to 450 (fighter)

**Comment by Jakob219** [comment]
adept range in builder phase is 375, tooltip says 475. fighter unit has 475 again

**Comment by OZEuncubeus** [comment]
violet in fighter phase should be 750, tooltip is correct

**Comment by Jakob219** [comment]
Phantom tooltip says 350 range, builderunit only has 250. fighter unit again has 350.

**Comment by Jakob219** [comment]
Forsaken one Tooltip says 90 range, i dunno on what we agreed, but its a melee unit with (apparently) 90 range.

**Comment by Jakob219** [comment]
Swamprunner says 420 hitpoints in tooltip, it has 600 tho in both builder and fighter phase

**Comment by Jakob219** [comment]
Hydra tooltip says -275 damage, but it only has -205 damage in both phases

**Comment by Jakob219** [comment]
Highborne tooltip only shows "Storm geysir" as ability, although it should also say "sphere" cause it has both abilities

**Comment by Jakob219** [comment]
Egg sack builderphase unit is 400, should be 250 tho

**Comment by Jakob219** [comment]
Komodo tooltip says correct attack-dmg value from only fighter unit, change builder unit to that value (81-92)

**Comment by Jakob219** [comment]
Tuskar spearman builder unit shows toopltip shows 16-17 attack dmg, but should have 26-27

**Comment by Jakob219** [comment]
Frostwolf tooltip say hp 200, should say 350.
builder unit has 350hp, fighter unit again has only 200 hp. should have 350!

**Comment by Jakob219** [comment]
azure dragon tooltip says 245-251 dmg, should say 245-260

**Comment by Jakob219** [comment]
Gateguard Tooltip sys 550 HP. Should say 650.

**Comment by Jakob219** [comment]
Fire Archer tooltip shows 17-20 damage, builder unit has 12-14, fighter unit has 17-19. change builder unit, tooltip and fighter unit to 17-19 damage.

Builder unit has 575 range, should be changed to 625.

**Comment by Jakob219** [comment]
Nightcrawlers Sticky Web tooltip says 

"Attacks slow enemies movement by 40% and attack by 30% for 6 seconds. Air units only"

Change to "Attacks slow enemies' Movement-Speed by 40% and Attack-Speed by 30% for 6 seconds. Air units only."

**Comment by Jakob219** [comment]
Hades fighter unit has 85-95 damage, tooltip says 75-95 and builder unit shows 70-80.

change all to 85-95

**Comment by OZEuncubeus** [comment]
Orc builder:

**Raider** Fighting phase 31-44 dmg 750hp, both tooltips attack/HP, builder + before round start incorrect.

**Orc warlock** Fighting phase 43-46 dmg 260 hp, Builder and before round start say 42-46dmg

**Comment by Jakob219** [comment]
Peasant tooltip show 175 HP, needs to change to 200.
