### ISSUE TITLE
Buff Destroyer

### ISSUE THREAD

**Issue by OZETobi** [Team-OZE/LegionTD-Map#16]
**Is your feature request related to a problem? Please describe.**
Destroyer is supposed to be a strong early-game roll. Currently it's a bit too weak.

**Describe the solution you'd like**
Buff HP to 1500 instead of 1300.

**Comment by OZETobi** [comment]
1550* instead of 1500.

**Comment by STOPTHECOUNT** [comment]
Done. Duplicate of #37.
