### ISSUE TITLE
Buff Elite Archer

### ISSUE THREAD

**Issue by OZETobi** [Team-OZE/LegionTD-Map#19]
**Is your feature request related to a problem? Please describe.**
Elite Archer is supposed to be a strong early game roll. Currently a bit too weak.

**Describe the solution you'd like**
Buff attackspeed by +10%. Buff HP +100.

**Comment by marcoabreu** [comment]
Alternativ proposal would be to give the archer more dmg onto the main target to make it more viable for lvl 10 and other focus mobs.

**Comment by OZEuncubeus** [comment]
> Alternativ proposal would be to give the archer more dmg onto the main target to make it more viable for lvl 10 and other focus mobs.

I wouldn't change it's niche, that change would do that, rather buff the total dmg imo.
