### ISSUE TITLE
Buff Hermit

### ISSUE THREAD

**Issue by OZETobi** [Team-OZE/LegionTD-Map#22]
**Is your feature request related to a problem? Please describe.**
We would like to see buffer-units become a bigger part of the meta - like Oracle. Currently u can't afford to build oracles before lvl 10 as it's usually not worth the cost.

**Describe the solution you'd like**
Decrease gold cost of Hermit from 110 to 90.

**Comment by OZEuncubeus** [comment]
Medicine man*
