### ISSUE TITLE
Make commonly used secondary game modes native

### ISSUE THREAD

**Issue by OZEuncubeus** [Team-OZE/LegionTD-Map#28]
Details are in the picture:
![Gamemodes overview4](https://user-images.githubusercontent.com/77214958/104497346-8060ef80-55da-11eb-92ed-c812e1449e24.png)

**Comment by marcoabreu** [comment]
Could you maybe write down what the standard would entail and the primary and secondary options which users are able to choose from? I'm having trouble interpreting the picture and list would be clearer to me.

**Comment by OZEuncubeus** [comment]
> Could you maybe write down what the standard would entail and the primary and secondary options which users are able to choose from? I'm having trouble interpreting the picture and list would be clearer to me.

I'm going to leave this here for raven, because he'll know better how to combine differents modes and how they ideally could be setup in the future. Also -MK should be added to the list.

**Comment by STOPTHECOUNT** [comment]
Resolved with updates #111
