### ISSUE TITLE
Wrong Tooltips

### ISSUE THREAD

**Issue by Jakob219** [Team-OZE/LegionTD-Map#61]
**The Following wrong tooltips has been found so far (there should be more probalbly):**

Necromancer/Necrolyte: Ability says "raise dead" instead of 'Mass dead" after build

Guard: Tooltip still cut below a certain resolution

Gnoll Warrior: Tooltip says 240hp, although its 230 (wont matter with balance change)

Komodo

Trident

Pyro/Destroyer unit incorrect

Warden tooltip says 10% evasion

**Comment by OZEuncubeus** [comment]
-Behemoth gives 5 not 3 bonus armor (tool-tip is wrong)

**Comment by STOPTHECOUNT** [comment]
It would help if you could write the texts for Komodo, Trident, Pyro/Destroyer

**Comment by STOPTHECOUNT** [comment]
All done in #111 except the ones that are in seperate issues.
