### ISSUE TITLE
Our v5 gradient map name isnt searchable in custom games.

### ISSUE THREAD

**Issue by OZEuncubeus** [Team-OZE/LegionTD-Map#8]
Our v5 map isn't searchable in custom games, possibly because of the gradient in it. Specifically people not being able to search the word 'legion' is worrisome. Maybe remove gradient from 'legion' only, since i don't think people search for any other terms.

**Comment by OZEuncubeus** [comment]
![Untitled123123](https://user-images.githubusercontent.com/77214958/104114973-9afd4500-530a-11eb-936c-092109e9bb32.png)

**Comment by r-mach** [comment]
> Possible fix:
> ![Untitled123123](https://user-images.githubusercontent.com/77214958/104114973-9afd4500-530a-11eb-936c-092109e9bb32.png)
> 
> ![Untitledteal](https://user-images.githubusercontent.com/77214958/104115035-32629800-530b-11eb-93ea-eea7d740912e.png)

If people just type `legion` maybe we could keep the "TD" with gradient ?

**Comment by OZEuncubeus** [comment]
Sure, that's fine too, whatever works for you to convert it into basic characters for the first word and keep it uniform at the same time 👍

**Comment by STOPTHECOUNT** [comment]
> 
> 
> > Possible fix:
> > ![Untitled123123](https://user-images.githubusercontent.com/77214958/104114973-9afd4500-530a-11eb-936c-092109e9bb32.png)
> > ![Untitledteal](https://user-images.githubusercontent.com/77214958/104115035-32629800-530b-11eb-93ea-eea7d740912e.png)
> 
> If people just type `legion` maybe we could keep the "TD" with gradient ?

Then it would be "searchable" but in the replay-section the map name would still look messed up (warcraft can't resolve the coding there for some reason).
I would personally prefer to remove the colors from lobby and replay section but leave them in-game and on results-page after the game.

**Comment by OZEuncubeus** [comment]
> > > Possible fix:
> > > ![Untitled123123](https://user-images.githubusercontent.com/77214958/104114973-9afd4500-530a-11eb-936c-092109e9bb32.png)
> > > ![Untitledteal](https://user-images.githubusercontent.com/77214958/104115035-32629800-530b-11eb-93ea-eea7d740912e.png)
> > 
> > 
> > If people just type `legion` maybe we could keep the "TD" with gradient ?
> 
> Then it would be "searchable" but in the replay-section the map name would still look messed up (warcraft can't resolve the coding there for some reason).
> I would personally prefer to remove the colors from lobby and replay section but leave them in-game and on results-page after the game.

I guess whatever works. If the map name is distorted anywhere functionally, it might be the better idea indeed :)

**Comment by STOPTHECOUNT** [comment]
Removed color coding from lobby and replay section. Now it's searchable and looks fine in replay section.
