### ISSUE TITLE
Make it possible to type game modes with caps (-BLABLA)

### ISSUE THREAD

**Issue by OZETobi** [Team-OZE/LegionTD-Map#98]
**Is your feature request related to a problem? Please describe.**
If host has caps on while typing game mode a remake needs to be made cuz it will give you the wrong mode.

**Describe the solution you'd like**
Make it possible to type game modes with caps.

**Comment by STOPTHECOUNT** [comment]
What's the desired behavior when you e.g. just write "-ar"?
Currently it activates a whole lot of other modes automatically.
Do you want to keep it that way?
Also modes like "cc" e.g. activate "gg". I guess there is some reason behind this, but it's not that easy to understand for the user.
